### PR TITLE
test suite, selector api doc, and wish list

### PR DESCRIPTION
**Pull request by dfkaye**
@aliirz 
I've added a short section on the README listing the supported selectors (and future selectors, maybe...), and created a tiny test suite.html to exercise them.  There's patched `assert` method in the suite as well.  No 3rd party test lib used.

On the README there's a link to the test suite viewable as a rawgit page ~ you'll need to modify the href to point to `aliirz` instead of `dfkaye`

### CODE REVIEW

**Comment by aliirz** [comment]
Wow Thank you. i am gonna test and merge this tonight

**Comment by aliirz** [comment]
@dfkaye I get the error `Uncaught TypeError: Illegal invocation` on the line

```
    !!ok || (typeof fn == 'function' || (fn = console.log)) && fn('fail: ' + msg);
```

When trying to run the test suite.

**Comment by dfkaye** [comment]
I've tried another pull request or update ~ not sure it made it.

If it didn't, just change line 32 to this:

```
!!ok || fn && fn('fail: ' + msg) || console.log('fail: ' + msg);
```

**Comment by aliirz** [comment]
Fixed. Cheers!

**Pull request merged**
